### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by justinruck080** [ebankoff/BoMbEr#3]
~/BoMbEr $ python BoMbEr.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/BoMbEr/BoMbEr.py", line 25, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
~/BoMbEr $

**Comment by HuErGa** [comment]
pip install selenium

**Comment by justinruck080** [comment]
2
Spammer started...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
Exception in thread Thread-3:
Traceback (most recent call last):
    self.run()
  File "/data/data/com.termux/files/usr/lib/python3.9/threading.py", line 910, in run
  File "/data/data/com.termux/files/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/data/data/com.termux/files/usr/lib/python3.9/threading.py", line 910, in run
  File "/data/data/com.termux/files/home/BoMbEr/BoMbEr.py", line 264, in start_spam
    phone9 = phone[1:]
TypeError: 'NoneType' object is not subscriptable
    self._target(*self._args, **self._kwargs)
  File "/data/data/com.termux/files/home/BoMbEr/BoMbEr.py", line 264, in start_spam
    phone9 = phone[1:]
TypeError: 'NoneType' object is not subscriptable

**Comment by HuErGa** [comment]
Please send a screenshot of the window with the program, where I can see what you are entering and what error is happening

**Comment by dedul4ik** [comment]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/BoMbEr/BoMbEr.py", line 11, in <module>
    import progressbar
ModuleNotFoundError: No module named 'progressbar'

**Comment by HuErGa** [comment]
Open cmd and write: pip install progressbar

**Comment by Hackersffh** [comment]
Exception in thread Thread-6 (start_spam):
Traceback (most recent call last):
Exception in thread Thread-7 (start_spam):
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
  File "/data/data/com.termux/files/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-8 (start_spam):
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
Exception in thread Thread-9 (start_spam):
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/data/data/com.termux/files/usr/lib/python3.10/threading.py", line 946, in run
Exception in thread Thread-10 (start_spam):
  File "/data/data/com.termux/files/usr/lib/python3.10/threading.py", line 946, in run
    self.run()
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/data/data/com.termux/files/home/BoMbEr/BoMbEr.py", line 264, in start_spam
    phone9 = phone[1:]
  File "/data/data/com.termux/files/home/BoMbEr/BoMbEr.py", line 264, in start_spam
  File "/data/data/com.termux/files/usr/lib/python3.10/threading.py", line 946, in run
TypeError: 'NoneType' object is not subscriptable
    self._target(*self._args, **self._kwargs)
  File "/data/data/com.termux/files/home/BoMbEr/BoMbEr.py", line 264, in start_spam
  File "/data/data/com.termux/files/usr/lib/python3.10/threading.py", line 946, in run
    self.run()
    phone9 = phone[1:]
TypeError: 'NoneType' object is not subscriptable
    self._target(*self._args, **self._kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/threading.py", line 946, in run
  File "/data/data/com.termux/files/home/BoMbEr/BoMbEr.py", line 264, in start_spam
    phone9 = phone[1:]
    self._target(*self._args, **self._kwargs)
TypeError: 'NoneType' object is not subscriptable
  File "/data/data/com.termux/files/home/BoMbEr/BoMbEr.py", line 264, in start_spam
    phone9 = phone[1:]
TypeError: 'NoneType' object is not subscriptable
    phone9 = phone[1:]
TypeError: 'NoneType' object is not subscriptable
